theme: jekyll-theme-slate
title: Geophysical Inversion
description: First course on inversion methods for geoscience undergraduates
name1: Matthew Piggott
address1: Room 4.82, Royal School of Mines
email1: m.d.piggott@imperial.ac.uk
github_username1:  matt-piggott
